"""Generate src/cleaning/script_ranges.py from DuckDB's RE2 Unicode tables (the tables the EDA script census used).

    python scripts/gen_script_ranges.py

Deriving the ranges from the same engine that produced reports/eda/text_quality_details.json means the Python script bitmask
can be verified against that census exactly (Phase 4 verification), rather than trusting hand-written block boundaries.
"""
import sys
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ['Latin', 'Devanagari', 'Bengali', 'Gurmukhi', 'Gujarati', 'Oriya', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Arabic', 'Cyrillic', 'Han']


def ranges_for(con, script):
    points = [r[0] for r in con.execute(
        f"SELECT i FROM range(0, 196608) t(i) WHERE i NOT BETWEEN 55296 AND 57343 AND regexp_matches(chr(i::INTEGER), '\\p{{{script}}}') ORDER BY i").fetchall()]
    out, start, prev = [], None, None
    for p in points:
        if start is None:
            start = prev = p
        elif p == prev + 1:
            prev = p
        else:
            out.append((start, prev))
            start = prev = p
    if start is not None:
        out.append((start, prev))
    return out


def main() -> int:
    con = duckdb.connect()
    lines = ['"""GENERATED by scripts/gen_script_ranges.py from DuckDB ' + duckdb.__version__ + ' RE2 \\\\p{Script} tables. Do not edit by hand.',
             '', 'Inclusive (first, last) code point ranges per script. Marks and digits of a script belong to it, as in the EDA census.', '"""', '',
             'SCRIPT_RANGES = {']
    for script in SCRIPTS:
        r = ranges_for(con, script)
        lines.append(f"    '{script}': (" + ', '.join(f'(0x{a:04X}, 0x{b:04X})' for a, b in r) + ',),')
        print(f'{script:11s} {len(r):2d} ranges, {sum(b - a + 1 for a, b in r):5d} code points')
    lines.append('}')
    (ROOT / 'src' / 'cleaning' / 'script_ranges.py').write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print('wrote src/cleaning/script_ranges.py')
    return 0


if __name__ == '__main__':
    sys.exit(main())
