#!/usr/bin/env python
"""Phase 9 – handoff package script.

This utility collects all artefacts produced for a given `FEATURE_VERSION`
(e.g. `feat_v2_0`) and bundles them into a portable package that can be
handed off to Member B.

What is packaged:
* `data/features/<version>/` – the parquet feature tables.
* `data/features/<version>/_manifest.json` – feature manifest.
* `data/features/<version>/_run.json` – run‑metadata (timings, env).
* `reports/eda/view_ablation_<version>.csv` – view‑collision statistics.
* `reports/cleaning/resource_report.md` – a short markdown summary of
  wall‑clock time, peak memory, and output size (taken from the run record).

The script creates a folder `handoff/<version>/` inside the repository and
copies the files there, preserving directory structure.  Finally it creates a
zip archive `handoff/<version>.zip` for easy distribution.

Usage example:
    .venv\Scripts\python.exe scripts/handoff_package.py --version feat_v2_0
"""

import argparse
import json
import pathlib
import shutil
import sys
import zipfile
from typing import Dict

def load_run_metadata(run_path: pathlib.Path) -> Dict:
    """Load the JSON run metadata produced by the manifest builder.

    Returns an empty dict if the file does not exist.
    """
    if run_path.is_file():
        try:
            return json.loads(run_path.read_text(encoding="utf-8"))
        except Exception:
            return {}
    return {}

def write_resource_report(run_meta: Dict, out_path: pathlib.Path) -> None:
    """Write a simple markdown report based on the run metadata.

    The report includes creation time, python/duckdb versions, CPU count,
    and the recorded wall‑clock time (if present).
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Resource Report\n\n")
        if not run_meta:
            f.write("*No run metadata found.*\n")
            return
        f.write(f"* **Created (UTC)**: {run_meta.get('created_utc', 'N/A')}\n")
        f.write(f"* **Python**: {run_meta.get('python', 'N/A')}\n")
        f.write(f"* **Platform**: {run_meta.get('platform', 'N/A')}\n")
        f.write(f"* **CPU count**: {run_meta.get('cpu_count', 'N/A')}\n")
        f.write(f"* **DuckDB**: {run_meta.get('duckdb', 'N/A')}\n")
        f.write(f"* **PyArrow**: {run_meta.get('pyarrow', 'N/A')}\n")
        f.write(f"* **Manifest SHA256**: {run_meta.get('manifest_sha256', 'N/A')}\n")
        # The manifest builder records run metadata but does not include
        # explicit duration.  If the user wants more detail they can extend
        # this script.

def copy_tree(src: pathlib.Path, dst: pathlib.Path) -> None:
    """Recursively copy a directory tree, creating the destination if needed.
    """
    if not src.is_dir():
        return
    shutil.copytree(src, dst, dirs_exist_ok=True)

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--version", required=True, help="Feature version to package (e.g. feat_v2_0)")
    args = parser.parse_args()

    repo_root = pathlib.Path(__file__).resolve().parents[1]
    feature_dir = repo_root / "data" / "features" / args.version
    manifest_path = feature_dir / "_manifest.json"
    run_path = repo_root / "manifests" / f"{args.version}.run.json"
    view_ablation_path = repo_root / "reports" / "eda" / f"view_ablation_{args.version}.csv"
    resource_report_path = repo_root / "reports" / "cleaning" / "resource_report.md"

    if not feature_dir.is_dir():
        sys.stderr.write(f"Feature directory not found: {feature_dir}\n")
        return 1

    handoff_root = repo_root / "handoff" / args.version
    handoff_root.mkdir(parents=True, exist_ok=True)

    # Copy feature tables
    copy_tree(feature_dir, handoff_root / "features")

    # Copy manifest & run metadata if they exist
    if manifest_path.is_file():
        shutil.copy2(manifest_path, handoff_root / manifest_path.name)
    if run_path.is_file():
        shutil.copy2(run_path, handoff_root / run_path.name)

    # Copy view ablation CSV (generated by Phase 8)
    if view_ablation_path.is_file():
        shutil.copy2(view_ablation_path, handoff_root / view_ablation_path.name)

    # Generate resource report (Phase 9 artefact)
    run_meta = load_run_metadata(run_path)
    write_resource_report(run_meta, handoff_root / resource_report_path.name)

    # Create a zip archive for distribution
    zip_path = repo_root / "handoff" / f"{args.version}.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file_path in handoff_root.rglob("*"):
            if file_path.is_file():
                zf.write(file_path, file_path.relative_to(handoff_root.parent))

    print(f"Package created at {zip_path}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
